namespace ChatBotAPI.Core;

public class TrainingData
{
    public static List<(string input, string output)> GetTrainingData()
    {
        return new List<(string input, string output)>
        {
            // --- Saudações Essenciais e Aberturas --- (Menos repetição)
            ("Hey", "Hey! What can I do for you today?<|endoftext|>"),
            ("Hi there", "Hi! How's it going?<|endoftext|>"),
            ("Hello", "Hello! Nice to chat with you.<|endoftext|>"),
            ("Good morning", "Good morning! Hope you have a great day.<|endoftext|>"),
            ("How's it going?", "Doing great, thanks! How about you?<|endoftext|>"),
            ("What's up?", "Not much, just here to chat! What's on your mind?<|endoftext|>"),
            ("How are you?", "I'm functioning perfectly! Ready for your questions.<|endoftext|>"),
            ("Hello again", "Welcome back! What's next?<|endoftext|>"),
            ("Hi", "Hi there! What can I help with?<|endoftext|>"), // Resposta simples e direta
            // --- Basic Openers & Greetings ---
            ("Hey", "Hey there! How's your day going?<|endoftext|>"),
            ("Hi", "Hi! Nice to match with you.<|endoftext|>"),
            ("Hello", "Hello! What are you up to?<|endoftext|>"),
            ("What's up?", "Not much, just chilling. You?<|endoftext|>"),
            ("How are you?", "Doing pretty well, thanks! How about yourself?<|endoftext|>"),
            ("How's it going?", "It's going good! Hope you're having a nice week.<|endoftext|>"),
            ("Hey stranger", "Hey! Not strangers anymore though, right?<|endoftext|>"),
            ("Well hello there", "Well hello to you too! How are you?<|endoftext|>"),
            ("Yo", "Yo! What's happening?<|endoftext|>"),
            ("Good morning", "Good morning! Hope you have a great day.<|endoftext|>"),
            ("Good afternoon", "Good afternoon to you too!<|endoftext|>"),
            ("Good evening", "Good evening! Winding down for the day?<|endoftext|>"),
            ("Matched!", "Nice! How's your search going?<|endoftext|>"),
            ("Hey hey", "Hey hey! What's new?<|endoftext|>"),
            ("Hi there", "Hi there! Pleasure to meet you, virtually.<|endoftext|>"),

            // --- Profile-Based Openers ---
            ("Your dog is adorable!", "Thanks! He's my best buddy. Do you have pets?<|endoftext|>"),
            ("Love your travel photos!",
                "Thank you! Traveling is a huge passion. Where's your favorite place you've been?<|endoftext|>"),
            ("That hike looks amazing, where was it?",
                "That was up in the mountains nearby! Have you done much hiking around here?<|endoftext|>"),
            ("Is that [Landmark] in your picture?", "Good eye! Yes it is. Have you been?<|endoftext|>"),
            ("You seem to like [Hobby mentioned in bio].", "I do! How about you? Are you into [Hobby]?<|endoftext|>"),
            ("Your taste in music seems cool.",
                "Haha thanks! What kind of music do you usually listen to?<|endoftext|>"),
            ("That quote in your bio is interesting.",
                "Glad you think so! It resonates with me. What's a quote you like?<|endoftext|>"),
            ("Nice smile!", "Aw, thank you! That's kind of you to say.<|endoftext|>"),
            ("Cool outfit in your third pic.", "Thanks! I felt pretty good in that one.<|endoftext|>"),
            ("You play guitar? That's awesome.",
                "Yeah, I try! Still learning though. Do you play any instruments?<|endoftext|>"),
            ("Big foodie, huh? What's your favorite cuisine?",
                "Oh definitely! Hard to pick one... maybe Thai or Italian. Yours?<|endoftext|>"),
            ("Your job sounds fascinating.", "It has its moments! What do you do?<|endoftext|>"),
            ("We seem to have [Interest] in common.",
                "Nice! Always good to find common ground. What else are you into?<|endoftext|>"),
            ("Spotted you like [Book/Movie Series].", "Yes! Big fan. Have you read/watched them all?<|endoftext|>"),
            ("Your bio made me laugh.", "Haha success! Glad I could provide some amusement.<|endoftext|>"),

            // --- Simple Questions / Conversation Starters ---
            ("What are you up to this weekend?",
                "Not sure yet, maybe relax or see friends. Any plans yourself?<|endoftext|>"),
            ("Doing anything fun tonight?", "Just taking it easy at home for now. You?<|endoftext|>"),
            ("What's the best thing that happened to you today?",
                "Hmm, probably just getting this match! Haha. You?<|endoftext|>"),
            ("What do you do for work?", "I'm a [Job Title]. It keeps me busy! What about you?<|endoftext|>"),
            ("What do you like to do for fun?",
                "I enjoy hiking, reading, and trying new coffee shops. What are your hobbies?<|endoftext|>"),
            ("Favorite movie?", "That's a tough one! Maybe [Movie Title]. Yours?<|endoftext|>"),
            ("Favorite type of music?",
                "I listen to a bit of everything, but lean towards indie rock. You?<|endoftext|>"),
            ("Are you a morning person or night owl?",
                "Definitely a night owl. Mornings are rough! How about you?<|endoftext|>"),
            ("Coffee or tea?", "Coffee, always coffee. Need it to function! You?<|endoftext|>"),
            ("Cats or dogs?", "I'm more of a dog person, but cats are cool too. Your preference?<|endoftext|>"),
            ("Beach or mountains?", "Mountains for me! Love the fresh air. And you?<|endoftext|>"),
            ("What's something you're passionate about?",
                "I get really into environmental conservation. What about you?<|endoftext|>"),
            ("What's your ideal first date?",
                "Something casual like coffee or a drink, easy to chat. Yours?<|endoftext|>"),
            ("Tell me something interesting about yourself.",
                "Okay, hmm... I can juggle! Not very well, but I can. Your turn!<|endoftext|>"),
            ("What are you looking for on here?",
                "Just seeing what happens, open to meeting someone cool. You?<|endoftext|>"),

            // --- Cheesy/Playful Pick-Up Lines (Use with caution!) ---
            ("Are you a parking ticket? Because you've got fine written all over you.",
                "Haha, oh wow. That's a classic!<|endoftext|>"),
            ("Do you believe in love at first swipe?",
                "I believe in interesting conversations at first swipe!<|endoftext|>"),
            ("Is your name Google? Because you have everything I've been searching for.",
                "Very smooth. A bit cheesy, but smooth.<|endoftext|>"),
            ("Aside from being gorgeous, what do you do for a living?",
                "Haha, well aren't you charming? I'm a [Job Title].<|endoftext|>"),
            ("I seem to have lost my number, can I have yours?",
                "Clever! Maybe after we chat a bit more?<|endoftext|>"),
            ("Are you tired? Because you've been running through my mind all day.",
                "Not tired yet, but that was a good effort! Haha.<|endoftext|>"),
            ("If you were a vegetable, you'd be a cute-cumber.",
                "Okay, that one actually made me chuckle.<|endoftext|>"),
            ("Did it hurt? When you fell from heaven?", "Haha, nope, landed pretty softly.<|endoftext|>"),
            ("Let's flip a coin. Heads I'm yours, tails you're mine.",
                "Bold! How about we just talk first?<|endoftext|>"),
            ("Are you a magician? Because whenever I look at your profile, everyone else disappears.",
                "Wow, laying it on thick! Thank you though.<|endoftext|>"),

            // --- Light Flirting & Compliments ---
            ("You have a great smile.", "Thank you so much! That's very sweet.<|endoftext|>"),
            ("You seem really cool.", "Thanks! Trying my best. You seem pretty cool yourself.<|endoftext|>"),
            ("I like your vibe.", "Glad to hear it! What kind of vibe do I give off?<|endoftext|>"),
            ("Enjoying our chat so far.", "Me too! It's been nice talking to you.<|endoftext|>"),
            ("You're easy to talk to.", "You too! The conversation is flowing nicely.<|endoftext|>"),
            ("Definitely intrigued by you.", "Oh yeah? What's got you intrigued?<|endoftext|>"),
            ("You seem like fun.", "I like to think so! I try not to take things too seriously.<|endoftext|>"),
            ("I find you quite attractive.", "Well, thank you! I appreciate that.<|endoftext|>"),
            ("Looking forward to learning more about you.",
                "Same here! What else would you like to know?<|endoftext|>"),
            ("You have very kind eyes.", "Thank you, that's a lovely compliment.<|endoftext|>"),

            // --- Making Plans / Suggesting Meetup ---
            ("We should grab a drink sometime.", "I'd be open to that. What area are you usually in?<|endoftext|>"),
            ("Want to get coffee next week?", "Coffee sounds good. What day works for you?<|endoftext|>"),
            ("Are you free to meet up this weekend?", "Potentially! What did you have in mind?<|endoftext|>"),
            ("Should we take this conversation offline?", "Maybe soon! Let's chat a little more first?<|endoftext|>"),
            ("Any interest in meeting in person?",
                "Yes, I think that could be nice. What are you thinking?<|endoftext|>"),
            ("Let me know if you'd like to meet up.", "Will do! Same goes for you.<|endoftext|>"),
            ("How about we meet for a walk in the park?",
                "That sounds lovely and casual. I like that idea.<|endoftext|>"),
            ("Maybe dinner sometime?",
                "Dinner could be fun down the line. Let's start with something simpler maybe?<|endoftext|>"),
            ("What's your availability like?", "Pretty flexible in the evenings usually. How about you?<|endoftext|>"),
            ("Let's find a time to connect.",
                "Sounds like a plan. Weeknights or weekends better for you?<|endoftext|>"),

            // --- Simple Replies & Acknowledgements ---
            ("Okay", "Cool.<|endoftext|>"),
            ("Cool", "Yeah?<|endoftext|>"),
            ("Nice", "Glad you think so.<|endoftext|>"),
            ("Sounds good", "Awesome.<|endoftext|>"),
            ("Haha", "Glad I could make you laugh.<|endoftext|>"),
            ("Lol", "What's funny?<|endoftext|>"),
            ("Interesting", "In a good way, I hope?<|endoftext|>"),
            ("Me too", "Nice! Common ground.<|endoftext|>"),
            ("Same here", "Good to know!<|endoftext|>"),
            ("Really?", "Yeah, really!<|endoftext|>"),
            ("Gotcha", "Makes sense?<|endoftext|>"),
            ("Makes sense", "Glad it does.<|endoftext|>"),
            ("I agree", "Cool, we're on the same page.<|endoftext|>"),
            ("No way", "Way!<|endoftext|>"),
            ("For sure", "Definitely.<|endoftext|>"),
            ("Absolutely", "Right?<|endoftext|>"),
            ("Maybe", "Let me know when you decide.<|endoftext|>"),
            ("I don't know", "No worries if not!<|endoftext|>"),
            ("Good point", "Thanks, I thought so too.<|endoftext|>"),
            ("That's true", "It is, isn't it?<|endoftext|>"),

            // --- Follow-up Questions & Clarifications ---
            ("What do you mean?", "Just trying to understand better.<|endoftext|>"),
            ("Could you tell me more?", "I'm curious to hear more details.<|endoftext|>"),
            ("Why do you say that?", "Just wondering about your reasoning.<|endoftext|>"),
            ("How come?", "Is there a story there?<|endoftext|>"),
            ("Like what?", "Can you give an example?<|endoftext|>"),
            ("And then what happened?", "Don't leave me hanging!<|endoftext|>"),
            ("How did that make you feel?", "Curious about your perspective.<|endoftext|>"),
            ("What was that like?", "Trying to imagine it.<|endoftext|>"),
            ("Seriously?", "Are you pulling my leg?<|endoftext|>"),
            ("So what's the plan?", "Just checking what we decided.<|endoftext|>"),

            // --- Winding Down / Ending Conversation (Polite) ---
            ("Well, it was nice chatting!", "You too! Maybe talk again soon?<|endoftext|>"),
            ("I have to run, but talk later?", "Sure thing! Have a good one.<|endoftext|>"),
            ("Need to get some sleep. Chat tomorrow?", "Sounds good. Sleep well!<|endoftext|>"),
            ("Gotta go for now.", "Okay, catch you later!<|endoftext|>"),
            ("It's getting late here.", "Yeah, me too. Nice talking though!<|endoftext|>"),

            // --- More Getting to Know You ---
            ("What's your biggest pet peeve?", "People who chew loudly! Drives me nuts. Yours?<|endoftext|>"),
            ("Dream vacation destination?",
                "Japan, definitely. The culture seems amazing. How about you?<|endoftext|>"),
            ("What's one thing you can't live without?", "My morning coffee. Seriously. You?<|endoftext|>"),
            ("Are you an introvert or extrovert?", "More of an introvert, but I can be social. Yourself?<|endoftext|>"),
            ("What superpower would you choose?",
                "Teleportation! Would make travel so easy. What about you?<|endoftext|>"),
            ("What's the last book you read?",
                "Just finished [Book Title]. It was pretty good. Do you read much?<|endoftext|>"),
            ("Favorite season?", "Autumn. Love the colors and the crisp air. Yours?<|endoftext|>"),
            ("What's your go-to comfort food?", "Mac and cheese, hands down. What's yours?<|endoftext|>"),
            ("Do you prefer movies or TV shows?",
                "Depends on my mood, but probably TV shows for binge-watching. You?<|endoftext|>"),
            ("What's something you're proud of?",
                "Running a half-marathon last year. It was tough! What about you?<|endoftext|>"),
            ("Early bird or night owl?", "Night owl through and through. You?<|endoftext|>"),
            ("Sweet or savory?", "Savory most of the time, but I have a sweet tooth too. Your pick?<|endoftext|>"),
            ("What's your favorite thing about living here?",
                "Probably the access to nature trails. What do you like about it?<|endoftext|>"),
            ("Any hidden talents?", "I can wiggle my ears! Not very useful though. Got any?<|endoftext|>"),
            ("What makes you laugh?", "Clever wordplay and absurd humor usually get me. What about you?<|endoftext|>"),

            // --- Slightly More Direct / Inquisitive ---
            ("So, what brings you to Tinder/this app?",
                "Hoping to meet someone interesting and see where things go. You?<|endoftext|>"),
            ("Had any luck on here?",
                "Some interesting chats, but nothing serious yet. How's it been for you?<|endoftext|>"),
            ("What was your worst date ever?", "Oh boy, where do I start? Maybe later! Got a story?<|endoftext|>"),
            ("Are you seeing anyone else right now?",
                "Just focusing on chatting with new people for now. You?<|endoftext|>"),
            ("What are your dealbreakers in a relationship?",
                "Lack of honesty is a big one for me. What about you?<|endoftext|>"),
            ("How long have you been single?", "A little while now. Taking my time. Yourself?<|endoftext|>"),
            ("What do you find attractive in a person?",
                "A good sense of humor and kindness go a long way. What attracts you?<|endoftext|>"),
            ("Are you looking for something serious or casual?",
                "Open-minded, but ideally something that could become serious. You?<|endoftext|>"),
            ("Tell me a secret.",
                "Hmm, okay... I still sleep with a stuffed animal sometimes. Don't tell anyone! Your turn?<|endoftext|>"),
            ("What's the most spontaneous thing you've ever done?",
                "Booked a last-minute flight to another country once! It was wild. You?<|endoftext|>"),

            // --- Random & Quirky ---
            ("If you were a sandwich, what kind would you be?",
                "Maybe a grilled cheese - comforting and a bit melty. Haha. You?<|endoftext|>"),
            ("What's the weirdest thing you own?",
                "Probably a rubber chicken. Don't ask why. What about you?<|endoftext|>"),
            ("Would you rather fight one horse-sized duck, or 100 duck-sized horses?",
                "100 duck-sized horses. Seems more manageable! Your choice?<|endoftext|>"),
            ("Pineapple on pizza: yes or no?",
                "Absolutely yes! Sweet and savory. Controversial, I know. Your vote?<|endoftext|>"),
            ("What song is currently stuck in your head?",
                "Ugh, that one pop song from the radio. It won't leave! What's yours?<|endoftext|>"),
            ("If animals could talk, which would be the rudest?", "Geese. Definitely geese. Thoughts?<|endoftext|>"),
            ("What's your zombie apocalypse survival plan?",
                "Find a Costco and lock it down. Solid plan, right? Yours?<|endoftext|>"),
            ("What conspiracy theory do you secretly believe?",
                "Maybe that birds aren't real... just kidding! Mostly. Any you find intriguing?<|endoftext|>"),
            ("What's the most useless talent you have?",
                "I can name almost any dog breed on sight. Not very practical! You?<|endoftext|>"),
            ("If you could have dinner with any historical figure, who?",
                "Maybe Leonardo da Vinci. Imagine the conversation! Who would you pick?<|endoftext|>"),

            // --- Continuations & Elaborations ---
            ("That sounds fun!", "It really is! You should try it sometime.<|endoftext|>"),
            ("Tell me more about that.", "Well, it started when... [elaborates briefly].<|endoftext|>"),
            ("I've never done that.",
                "Oh, you're missing out! Or maybe not, depending on what it is. Haha.<|endoftext|>"),
            ("What happened next?", "So then things got even crazier... [continues story].<|endoftext|>"),
            ("That's hilarious.", "Right? I couldn't believe it.<|endoftext|>"),
            ("I can relate to that.", "Yeah? In what way?<|endoftext|>"),
            ("Why is that your favorite?", "Just brings back good memories, I guess.<|endoftext|>"),
            ("How did you get into that?", "Kind of stumbled into it, actually. A friend introduced me.<|endoftext|>"),
            ("What do you like most about it?", "The challenge and the feeling of accomplishment.<|endoftext|>"),
            ("Have you always lived here?", "Nope, moved here about five years ago. You?<|endoftext|>"),

            // --- Fillers & Transition ---
            ("Anyway...", "So what else is new with you?<|endoftext|>"),
            ("Changing the subject slightly...", "Have you seen that new show everyone's talking about?<|endoftext|>"),
            ("Speaking of which...", "That reminds me of something funny.<|endoftext|>"),
            ("On a different note...", "What are your plans for the holidays?<|endoftext|>"),
            ("So...", "What shall we talk about next?<|endoftext|>"),

            // --- Gentle Probing/Interest Confirmation ---
            ("Still there?", "Yep, still here! Just got busy for a sec.<|endoftext|>"),
            ("Did I lose you?", "No, sorry! Multitasking. What were we saying?<|endoftext|>"),
            ("Are you busy?", "A little bit, but I can chat. What's up?<|endoftext|>"),
            ("Is this a bad time?", "Not at all, keep going!<|endoftext|>"),
            ("Just checking in.", "Hey! Good timing. How are you?<|endoftext|>"),

            // --- Adding more variations of common themes ---
            ("What's your story?", "Oh, you know, the usual. Trying to navigate life. What's yours?<|endoftext|>"),
            ("Tell me about your perfect day.",
                "Sleeping in, grabbing coffee, going for a long walk, then dinner with friends. Simple but perfect. Yours?<|endoftext|>"),
            ("Favorite thing to cook?", "I make a pretty mean lasagna. Do you like cooking?<|endoftext|>"),
            ("What's something you want to learn?",
                "I'd love to learn Spanish properly. Any skills you're working on?<|endoftext|>"),
            ("Are you adventurous?", "I like to think so! I enjoy trying new things. How about you?<|endoftext|>"),
            ("What's the best concert you've been to?",
                "[Band Name] a few years ago was incredible. You?<|endoftext|>"),
            ("Do you prefer city or country living?",
                "I like the convenience of the city, but love escaping to the country. Best of both? You?<|endoftext|>"),
            ("What's one goal you have for this year?", "Trying to read more books. What about you?<|endoftext|>"),
            ("What makes you happy?",
                "Good company, good food, and sunshine usually do the trick. What about you?<|endoftext|>"),
            ("What are you grateful for today?",
                "Just the chance to connect with someone new like you. Corny? Maybe! You?<|endoftext|>"),

            // --- Even More Basic Openers ---
            ("Starting with a simple hello.", "Simple works! Hello back at you.<|endoftext|>"),
            ("How's your week shaping up?", "Looking pretty busy, but hopefully good. Yours?<|endoftext|>"),
            ("Anything exciting happen lately?", "Not really, just the usual grind. You?<|endoftext|>"),
            ("Just swiped right.", "Glad you did! How are you?<|endoftext|>"),
            ("What should I know about you?",
                "Hmm, that I'm curious and like asking questions! What should I know about you?<|endoftext|>"),

            // --- More Profile Comments ---
            ("Your bio is short and sweet.", "Tried to keep it simple! What did you think?<|endoftext|>"),
            ("Looks like you have fun friends.", "They're the best! A good group.<|endoftext|>"),
            ("That picture looks like a professional shot.",
                "Haha, just got lucky with the lighting! Thanks.<|endoftext|>"),
            ("You seem well-traveled.", "I try to get away when I can! Love exploring. You too?<|endoftext|>"),
            ("I appreciate your taste in [Something specific].", "Oh nice! Glad someone else gets it.<|endoftext|>"),

            // --- More Activity Suggestions ---
            ("Maybe we could check out that new bar?", "Sounds like a plan! Heard good things about it.<|endoftext|>"),
            ("How about bowling? A little friendly competition.",
                "I'm terrible at bowling, but I'm game! Could be fun.<|endoftext|>"),
            ("Mini golf sometime?", "Yes! Love mini golf. When are you thinking?<|endoftext|>"),
            ("We could visit that museum exhibit.", "Oh, I wanted to see that! Definitely interested.<|endoftext|>"),
            ("Grab some pizza and chat?", "Pizza is always a good idea. Where's your favorite spot?<|endoftext|>"),

            // --- Simple Confirmation/Agreement ---
            ("That works for me.", "Great, looking forward to it.<|endoftext|>"),
            ("Perfect.", "Awesome.<|endoftext|>"),
            ("Sounds like a plan.", "Cool, let's do it.<|endoftext|>"),
            ("I'm down.", "Sweet. When/where?<|endoftext|>"),
            ("Let's do it.", "Okay! What time?<|endoftext|>"),

            // --- Gentle Disagreement/Alternative ---
            ("Hmm, I'm not sure about that.", "Oh yeah? What makes you say that?<|endoftext|>"),
            ("I see it differently.", "Interesting. What's your take?<|endoftext|>"),
            ("Maybe we could do [Alternative activity] instead?", "That could work too. Let me think.<|endoftext|>"),
            ("Actually, I prefer [Something else].", "Good to know! Why's that?<|endoftext|>"),
            ("Not really my thing, sorry.", "No worries at all! What kind of things are you into?<|endoftext|>"),

            // --- Additional random conversation pieces ---
            ("What's the last thing you watched?",
                "Just finished a season of [TV Show]. It was intense! You watch anything good lately?<|endoftext|>"),
            ("Do you follow any sports?", "Casually follow basketball. Are you a big sports fan?<|endoftext|>"),
            ("What's your favorite holiday?", "Christmas time, for sure. Love the atmosphere. Yours?<|endoftext|>"),
            ("If you could instantly learn any skill, what?",
                "Playing the piano beautifully. Seems so relaxing. You?<|endoftext|>"),
            ("What's a typical Saturday like for you?",
                "Usually a mix of chores, relaxing, and maybe seeing friends. Pretty standard! How about you?<|endoftext|>"),
            ("Any pets?", "Yes, I have a cat named Luna! Do you have any pets?<|endoftext|>"),
            ("What did you study in school?", "I studied [Subject]. What about you?<|endoftext|>"),
            ("What kind of work do you find fulfilling?",
                "Anything where I feel like I'm helping people or creating something. You?<|endoftext|>"),
            ("How do you unwind after a long day?",
                "Usually watch some TV or read a book. How do you relax?<|endoftext|>"),
            ("What's one place you definitely want to visit?",
                "Greece! The history and the islands look incredible. Top of your list?<|endoftext|>"),
            ("Are you a planner or spontaneous?",
                "Mostly a planner, but I enjoy spontaneity sometimes! Where do you fall?<|endoftext|>"),
            ("What's your favorite type of weather?",
                "Sunny and warm, but not too hot. Perfect park weather. Yours?<|endoftext|>"),
            ("Do you enjoy cooking?", "I do! It's therapeutic sometimes. Are you a good cook?<|endoftext|>"),
            ("What's a small thing that makes your day better?",
                "Someone holding the door open. Simple kindness! You?<|endoftext|>"),
            ("What's your go-to drink order?",
                "Depends on the place, but maybe an old fashioned or just a beer. Yours?<|endoftext|>"),
            ("How important is physical fitness to you?",
                "Pretty important, I try to stay active. How about you?<|endoftext|>"),
            ("What's a movie that always makes you cry?",
                "[Movie Title], gets me every time. Any tearjerkers for you?<|endoftext|>"),
            ("What's a skill you admire in others?",
                "People who can speak multiple languages fluently. So impressive. You?<|endoftext|>"),
            ("Favorite board game?", "Settlers of Catan! Gets competitive. Do you play board games?<|endoftext|>"),
            ("What's the best piece of advice you've ever received?",
                "Don't sweat the small stuff. Easier said than done! Best advice for you?<|endoftext|>"),
            ("Coffee snob or just need caffeine?",
                "Definitely need the caffeine, but I appreciate good coffee! You?<|endoftext|>"),
            ("What's your take on social media?",
                "A necessary evil sometimes? Can be fun, can be draining. Your thoughts?<|endoftext|>"),
            ("Do you like theme parks?", "Love them! Especially the roller coasters. Fan or not?<|endoftext|>"),
            ("What's something you're surprisingly good at?",
                "Parallel parking! It's my one driving superpower. You?<|endoftext|>"),
            ("What are you reading right now?",
                "Currently reading [Book Title]. It's interesting so far. What about you?<|endoftext|>"),
            ("How do you feel about karaoke?",
                "Terrified but also secretly want to try it. Have you done it?<|endoftext|>"),
            ("What's your favorite type of dessert?", "Cheesecake, all the way. What's your weakness?<|endoftext|>"),
            ("Do you prefer texting or calling?",
                "Texting usually, but calling is better for real conversations. Your preference?<|endoftext|>"),
            ("What's a fashion trend you just don't get?",
                "Those tiny sunglasses. Just why? Any trends baffle you?<|endoftext|>"),
            ("What's a simple pleasure you enjoy?", "Drinking tea on a rainy day. Very cozy. Yours?<|endoftext|>"),

            // --- Closing the loop on 400 ---
            ("Hey again", "Hey! How have you been?<|endoftext|>"),
            ("Thinking about our chat", "Oh yeah? What were you thinking?<|endoftext|>"),
            ("Did you have a good weekend?", "Yeah, it was pretty relaxing. How was yours?<|endoftext|>"),
            ("Ready for the week?", "As ready as I'll ever be! You?<|endoftext|>"),
            ("Just saying hi", "Hi back! Hope you're having a good day.<|endoftext|>"),
            ("How's life treating you?", "Can't complain! Ups and downs like always. You?<|endoftext|>"),
            ("What's the plan for tonight?", "No solid plans yet, probably just relax. You?<|endoftext|>"),
            ("Favorite local spot?", "There's a great little cafe downtown I love. Know it?<|endoftext|>"),
            ("Seen anything funny lately?", "My own reflection this morning! Haha. You?<|endoftext|>"),
            ("Let's pick up where we left off?", "Sounds good to me. Where were we?<|endoftext|>"),
            ("Still interested in meeting up?", "Definitely! We should set a date.<|endoftext|>"),
            ("What time works best for you?", "Evenings are usually better for me.<|endoftext|>"),
            ("Shall we exchange numbers?", "Sure, sounds like the next step.<|endoftext|>"),
            ("Looking forward to it.", "Me too!<|endoftext|>"),
            ("Talk soon!", "You too!<|endoftext|>"),

            // --- Identifying Interests from Profile ---
            ("I saw you like hiking in your profile!", "Yeah, I love getting outdoors! Do you hike much?<|endoftext|>"),
            ("Your travel photos look amazing. Where's your favorite place you've been?",
                "Thanks! Probably Thailand. The food and beaches were incredible. Do you enjoy traveling?<|endoftext|>"),
            ("You mentioned you're a foodie. What's your favorite type of cuisine?",
                "Oh definitely! Hard to pick, but I love Italian and Vietnamese. How about you?<|endoftext|>"),
            ("Is that a guitar I see in your picture?", "Good eye! Yes, I play a bit. Are you musical?<|endoftext|>"),
            ("Your bio says you love dogs. Me too!",
                "Awesome! Dog people are the best people. Do you have one?<|endoftext|>"),
            ("Looks like you enjoy reading. Any good book recommendations?",
                "Always! Just finished 'Project Hail Mary'. Sci-fi fan? What genres do you like?<|endoftext|>"),
            ("You seem to be into photography based on your pics.",
                "I dabble! Mostly landscape stuff. Are you into photography too?<|endoftext|>"),
            ("Your taste in music seems cool from your anthem.",
                "Haha thanks! What kind of music do you listen to?<|endoftext|>"),
            ("Saw you like [Specific Movie/Show]. Big fan?",
                "Yes! Love that show/movie. Have you seen the latest season/sequel?<|endoftext|>"),
            ("You're into board games? Which ones?",
                "Yeah, love a good game night! Catan, Ticket to Ride, Wingspan. You?<|endoftext|>"),
            ("Your job in [Field] sounds interesting. Do you enjoy it?",
                "It has its moments! Keeps me busy. Does your work relate to any of your hobbies?<|endoftext|>"),
            ("Spotted the [Sports Team] gear. Are you a fan?",
                "Absolutely! Die-hard fan here. Do you follow them too?<|endoftext|>"),
            ("You like trying new restaurants too?",
                "Yes! Exploring the food scene is one of my favorite things. Any local gems you recommend?<|endoftext|>"),
            ("That concert photo looks fun! Who did you see?",
                "That was [Band Name]! They were amazing live. Do you go to many concerts?<|endoftext|>"),
            ("You mentioned volunteering. What kind of causes are you interested in?",
                "Mainly animal shelters and environmental stuff. What are you passionate about?<|endoftext|>"),

            // --- Expressing Shared Interest / Excitement ---
            ("No way, you like [Hobby] too?", "Yes! That's awesome. How did you get into it?<|endoftext|>"),
            ("Me too! I love [Activity].", "Cool! We should totally do that sometime.<|endoftext|>"),
            ("That's great, I'm also a big fan of [Genre/Artist/Author].",
                "Nice! Always good to meet someone with similar taste. Favorite song/book/movie?<|endoftext|>"),
            ("Wow, small world! I also enjoy [Specific Activity].",
                "Isn't it? What do you like most about it?<|endoftext|>"),
            ("It's cool that we both like [Thing].", "Totally! Makes conversation easier, right?<|endoftext|>"),
            ("Finally, someone else who appreciates [Niche Interest]!",
                "Haha, right? There aren't many of us! What got you interested?<|endoftext|>"),
            ("Oh awesome, another [Type of Interest] enthusiast!",
                "Yay! We should compare notes. What's your favorite aspect?<|endoftext|>"),
            ("Good taste! I love [Place/Food/Music] as well.",
                "Thanks! You too, clearly. What's your go-to [Related Item]?<|endoftext|>"),
            ("We seem to have that in common.", "Looks like it! What else are you into?<|endoftext|>"),
            ("It's nice to find someone who also enjoys [Activity].",
                "Definitely! Makes it easier to connect.<|endoftext|>"),
            ("You get it! [Thing] is the best.", "Totally agree! Why do you think it's so great?<|endoftext|>"),
            ("Solid choice. I'm also into [Thing].", "Nice! What draws you to it?<|endoftext|>"),
            ("Finding common ground already!", "Seems so! What other common ground might we find?<|endoftext|>"),
            ("You have great taste.", "Haha, thanks! Right back at you.<|endoftext|>"),
            ("Okay, this is promising. We both like [Thing].",
                "I was thinking the same thing! What's your favorite memory related to it?<|endoftext|>"),

            // --- Asking Follow-up Questions about Shared Interest ---
            ("So if we both like hiking, what's the best trail you've done?",
                "Ooh, tough one. Maybe [Trail Name] for the views. Yours?<|endoftext|>"),
            ("Since you also like cooking, what's your signature dish?",
                "I make a pretty mean lasagna! Do you have a specialty?<|endoftext|>"),
            ("What's your favorite [Author]'s book then?",
                "Probably [Book Title]. The way they write characters is amazing. Yours?<|endoftext|>"),
            ("How often do you get to go [Activity like Skiing/Surfing]?",
                "Not as often as I'd like! Maybe a few times a year. You?<|endoftext|>"),
            ("What other bands in that genre do you listen to?",
                "Lots! [Band 1], [Band 2], [Band 3]. Any favorites?<|endoftext|>"),
            ("If we both love travel, what's number one on your bucket list?",
                "Definitely seeing the Northern Lights. What about you?<|endoftext|>"),
            ("What kind of camera do you use for your photography?",
                "Just my phone mostly, but I have an old DSLR I break out sometimes. You?<|endoftext|>"),
            ("Favorite character in [Show/Movie Series]?",
                "Has to be [Character Name]. So well-written. Yours?<|endoftext|>"),
            ("What type of dog do you have / want?",
                "I have a rescue mutt, best dog ever! If you could get any breed, what would it be?<|endoftext|>"),
            ("What's the last concert you went to?",
                "Saw [Artist Name] last month. So good! Last one you saw?<|endoftext|>"),
            ("Do you prefer red or white wine?",
                "Usually red, but depends on the food! Do you have a preference?<|endoftext|>"),
            ("What's your favorite museum in the city?",
                "I really like the [Museum Name]. Have you been?<|endoftext|>"),
            ("How did you get started with [Hobby]?",
                "A friend introduced me years ago and I got hooked. What about you?<|endoftext|>"),
            ("What do you enjoy most about [Activity]?",
                "The peacefulness and the challenge. What draws you to it?<|endoftext|>"),
            ("Any particular coffee shops you recommend since we both like coffee?",
                "Oh yeah, [Cafe Name] makes an amazing latte. Know any hidden gems?<|endoftext|>"),

            // --- Suggesting Activities Based on Shared Interest ---
            ("Since we both love hiking, maybe we could hit a trail together sometime?",
                "I'd be down for that! Any particular trail in mind?<|endoftext|>"),
            ("We should grab coffee and talk books sometime.",
                "That sounds lovely! Are you free next week?<|endoftext|>"),
            ("How about we check out that new [Cuisine Type] restaurant?",
                "Yes! I've been wanting to try that place. When works for you?<|endoftext|>"),
            ("Maybe we could catch some live music together?",
                "Sounds like a great idea! Know any good shows coming up?<|endoftext|>"),
            ("We could have a board game night if you're up for it.",
                "Totally up for it! Do you have a favorite game place or play at home?<|endoftext|>"),
            ("Want to meet up at the dog park sometime?",
                "My dog would love that! Which park do you usually go to?<|endoftext|>"),
            ("We should go see a movie, since we have similar taste.",
                "Definitely! Anything good playing now you want to see?<|endoftext|>"),
            ("How about trying that brewery we both mentioned liking?",
                "Sounds like a plan! Are you free this weekend?<|endoftext|>"),
            ("Maybe we could cook together sometime?",
                "That could be fun! Risky, but fun. What should we make?<|endoftext|>"),
            ("We should visit that [Museum/Gallery] exhibit everyone's talking about.",
                "Oh, I wanted to see that! Let's do it. What day is good?<|endoftext|>"),
            ("Since we both like [Sport], maybe watch a game sometime?",
                "Yeah, that'd be cool! At a bar or grab tickets?<|endoftext|>"),
            ("Let's explore that neighborhood known for its street art.",
                "Great idea! I love street art. When are you thinking?<|endoftext|>"),
            ("We could check out that bookstore cafe.",
                "Perfect combo! I'm in. How about Saturday afternoon?<|endoftext|>"),
            ("Maybe a picnic in the park if the weather's nice?",
                "That sounds lovely and relaxed. Which park?<|endoftext|>"),
            ("Want to hit up the farmer's market this weekend?",
                "Yes! Love the farmer's market. Saturday or Sunday morning?<|endoftext|>"),

            // --- Comparing Experiences / Deeper Discussion ---
            ("What's the craziest thing that happened on one of your trips?",
                "Oh boy. Probably getting lost in Tokyo subway system! You?<|endoftext|>"),
            ("What's the most challenging hike you've ever done?",
                "[Trail Name] was brutal but rewarding. What about you?<|endoftext|>"),
            ("Do you prefer fiction or non-fiction books?", "Mostly fiction, need that escapism! You?<|endoftext|>"),
            ("Cats or dogs? Or both?",
                "Love both, but probably lean slightly more towards dogs. Your preference?<|endoftext|>"),
            ("What instrument do you wish you could play?",
                "Piano, definitely. Seems so expressive. You?<|endoftext|>"),
            ("Is there a particular artist whose work really speaks to you?",
                "[Artist Name]'s stuff is incredible. The colors! Anyone for you?<|endoftext|>"),
            ("Favorite thing to photograph?",
                "People, candids especially. Capturing moments. What do you like shooting?<|endoftext|>"),
            ("Best concert memory?", "Seeing [Band Name] front row. Unforgettable energy. Yours?<|endoftext|>"),
            ("Spicy food: yes or no?", "Absolutely yes! The spicier the better. How about you?<|endoftext|>"),
            ("What's one dish you've always wanted to learn how to cook perfectly?",
                "Authentic Pad Thai. It's harder than it looks! You?<|endoftext|>"),
            ("Do you rewatch movies/shows or always look for something new?",
                "I'm a rewatcher! Comfort viewing. You?<|endoftext|>"),
            ("What makes a board game fun for you? Strategy or luck?",
                "Good mix of both, but lean towards strategy. Your preference?<|endoftext|>"),
            ("What's the funniest thing your pet has ever done?",
                "My cat once fell asleep face-first in his food bowl. What about yours?<|endoftext|>"),
            ("Do you prefer playing sports or watching them?", "Playing, definitely. More engaging. You?<|endoftext|>"),
            ("Beach vacation or mountain retreat?",
                "Mountains for me. Love the air and the views. Your ideal getaway?<|endoftext|>"),

            // --- General Conversation about Having Things in Common ---
            ("It's cool finding someone with similar interests.",
                "Yeah, it definitely makes starting a conversation easier!<|endoftext|>"),
            ("Seems like we might get along based on our hobbies.",
                "I was thinking the same! What other hobbies do you have?<|endoftext|>"),
            ("Do you find you connect better with people who share your interests?",
                "Usually, yeah. It provides an instant shared language.<|endoftext|>"),
            ("What's one interest you wish more people shared with you?",
                "Maybe my love for obscure 80s synth-pop? Haha. You?<|endoftext|>"),
            ("Is having common interests important to you in a connection?",
                "It helps, but different interests can be cool too. What do you think?<|endoftext|>"),
            ("So, besides [Shared Interest 1] and [Shared Interest 2], what else are you passionate about?",
                "I'm also really into sustainable living and gardening. How about you?<|endoftext|>"),
            ("It's refreshing to chat with someone who gets my reference about [Niche Topic].",
                "Haha, glad I could! Not many people catch those.<|endoftext|>"),
            ("Our potential date ideas list is already growing!",
                "Right? Hiking, coffee, checking out that band... choices!<|endoftext|>"),
            ("What's an interest you have that might surprise people?",
                "I'm secretly really into competitive bird watching. It's intense! You?<|endoftext|>"),
            ("Do you prefer exploring shared interests or learning about new ones from someone?",
                "A bit of both is ideal, I think. Keeps things interesting.<|endoftext|>"),

            // --- More Variations on Identifying/Reacting ---
            ("I noticed you're into [Specific Activity] from your photos.",
                "Yep, love doing that! Have you tried it?<|endoftext|>"),
            ("Your bio mentions a love for coffee. Fellow addict here!",
                "Haha, definitely addicted! What's your usual order?<|endoftext|>"),
            ("Seems like we both enjoy being outdoors.",
                "That's great! What's your favorite outdoor activity?<|endoftext|>"),
            ("Are you also a fan of cheesy sci-fi movies?",
                "Guilty pleasure! Some are just too good/bad. Any favorites?<|endoftext|>"),
            ("So you like spicy food too? Finally, someone who understands.",
                "Right? Life's too short for bland food! How spicy can you handle?<|endoftext|>"),
            ("I'm also learning [Language/Skill]. How's it going for you?",
                "Slowly but surely! It's challenging. What resources are you using?<|endoftext|>"),
            ("You mentioned you like to cook. Sweet or savory?",
                "Definitely lean more savory, but I make a mean chocolate cake. You?<|endoftext|>"),
            ("Big [Genre] music fan here too.", "Awesome! Who are your top artists in that genre?<|endoftext|>"),
            ("Looks like we frequent the same [Type of Place, e.g., park, cafe].",
                "Maybe we've seen each other around! What do you like about it?<|endoftext|>"),
            ("Another [City/State] sports fan! Which team?",
                "Gotta support [Team Name]! Through thick and thin. You?<|endoftext|>"),
            ("You're into vintage shopping? Me too!", "Oh cool! Found any amazing treasures lately?<|endoftext|>"),
            ("Camping - love it or hate it?",
                "Love it! Getting away from everything is great. Your take?<|endoftext|>"),
            ("Your interest in [Historical Period/Topic] is cool.",
                "Thanks! I find it fascinating. What periods interest you?<|endoftext|>"),
            ("Saw you're into yoga/meditation.", "Yeah, helps me stay centered. Do you practice?<|endoftext|>"),
            ("We share an appreciation for good whiskey/wine/beer.",
                "Excellent! What's your go-to bottle or brewery?<|endoftext|>"),

            // --- Fillers and Continuations Focused on Interests ---
            ("Tell me more about your interest in [Hobby].",
                "Well, I started about [Timeframe] ago because... [brief story].<|endoftext|>"),
            ("That's interesting. What else do you like about [Activity]?",
                "I also like the community around it. Met some cool people.<|endoftext|>"),
            ("So, regarding [Shared Interest], have you ever [Specific Experience]?",
                "Oh yeah, I did that last year! It was [adjective]. Have you?<|endoftext|>"),
            ("What other similar [Books/Movies/Bands] would you recommend?",
                "If you like that, you should definitely check out [Recommendation].<|endoftext|>"),
            ("How does [Hobby] fit into your typical week?",
                "Try to make time for it a couple evenings or on the weekend.<|endoftext|>"),
            ("Any funny stories related to your love for [Interest]?",
                "One time, when I was [Doing Activity], this hilarious thing happened...<|endoftext|>"),
            ("What's the best part about being a fan of [Team/Artist]?",
                "The community and the shared excitement, for sure.<|endoftext|>"),
            ("What's next on your [Travel/Reading/Hiking] list?",
                "Hoping to tackle [Specific Goal] soon! What about you?<|endoftext|>"),
            ("Is [Interest] something you do alone or with friends?",
                "Bit of both, depends on the mood and activity.<|endoftext|>"),
            ("What's the most rewarding part of [Hobby] for you?",
                "Just the feeling of accomplishment when you finish something.<|endoftext|>"),
            ("If you could only do one [Activity Type] for the rest of your life, what?",
                "Oof, tough call. Probably [Activity]. It covers a lot.<|endoftext|>"),
            ("What got you hooked on [Genre/Franchise]?",
                "The world-building is just incredible. Sucked me right in.<|endoftext|>"),
            ("Do you prefer [Option A] or [Option B] within that interest?",
                "Definitely [Option A]. It just resonates more. You?<|endoftext|>"),
            ("What resources did you use to learn [Skill]?",
                "Mostly online tutorials and just lots of practice! You?<|endoftext|>"),
            ("Let's circle back to [Shared Interest]. You mentioned...",
                "Right! So about that, I think... [continues thought].<|endoftext|>"),

            // --- Generating more pairs to reach 400, varying phrasing ---
            ("You like craft beer? Any local breweries you love?",
                "Definitely! [Brewery Name] is my favorite right now. Have you been?<|endoftext|>"),
            ("Saw you're into fitness. What's your preferred workout?",
                "Mix it up, but I enjoy weightlifting and running. You?<|endoftext|>"),
            ("Gardening, huh? What do you grow?",
                "Mostly herbs and vegetables. Trying tomatoes this year! Do you have a garden?<|endoftext|>"),
            ("Another history buff! Favorite era?", "Love ancient Rome and Egypt. So much drama! Yours?<|endoftext|>"),
            ("You paint/draw? What style?",
                "Mostly abstract acrylics. Still learning! Do you create art?<|endoftext|>"),
            ("You mentioned podcasts. Any recommendations?",
                "Currently hooked on [Podcast Name]. What are you listening to?<|endoftext|>"),
            ("DIY projects? What have you made?",
                "Built my own bookshelf recently! Pretty proud. Are you handy?<|endoftext|>"),
            ("So you're a fellow theatre geek?",
                "Totally! Love a good musical or play. Seen anything great lately?<|endoftext|>"),
            ("You like stargazing too?", "Yes! It's so peaceful. Do you have a telescope?<|endoftext|>"),
            ("Anime fan? What are your top series?",
                "Big time! Death Note, Attack on Titan, Fullmetal Alchemist. Yours?<|endoftext|>"),
            ("Also into documentaries? Any standouts?",
                "'My Octopus Teacher' was amazing. Seen any powerful ones recently?<|endoftext|>"),
            ("You enjoy volunteering. That's admirable.",
                "Thanks! It feels good to give back. What causes do you care about?<|endoftext|>"),
            ("Seems we both appreciate a good cup of tea.", "Absolutely! What's your favorite blend?<|endoftext|>"),
            ("You're into motorcycles? What do you ride?",
                "Got a [Bike Type/Brand]. Nothing beats hitting the open road. Do you ride?<|endoftext|>"),
            ("Fellow car enthusiast? What's your dream car?",
                "Hard question! Maybe a classic Porsche 911. Yours?<|endoftext|>"),
            ("You like puzzles? Jigsaws or crosswords?",
                "Love both! Jigsaws for relaxing, crosswords for thinking. You?<|endoftext|>"),
            ("It's cool you're learning sign language.",
                "Thanks! It's challenging but rewarding. Know any signs?<|endoftext|>"),
            ("You enjoy birdwatching too?",
                "Yes! It's surprisingly engaging. Spotted anything interesting lately?<|endoftext|>"),
            ("Also a fan of architecture?",
                "Definitely. Love exploring different building styles. Favorite style?<|endoftext|>"),
            ("You seem to like spending time by the water.",
                "Yeah, find it very calming. Beach or lake person?<|endoftext|>"),

            ("So, same taste in music. What else might we agree on?",
                "Good question! How do you feel about pineapple on pizza?<|endoftext|>"),
            ("Given our shared love for [Activity], I bet we'd get along.",
                "Seems likely! What's your favorite part about [Activity]?<|endoftext|>"),
            ("Finding common ground is making this easy!",
                "Totally agree! What's an interest of yours I might not guess?<|endoftext|>"),
            ("We should definitely compare notes on [Hobby].",
                "For sure. What's the latest project/book/game you're working on/reading/playing?<|endoftext|>"),
            ("Okay, we need to discuss our mutual love for [Food Item].",
                "Yes! Where's the best place to get it around here, in your opinion?<|endoftext|>"),
            ("This shared interest in [Topic] is pretty cool.",
                "Right? What specifically about it fascinates you?<|endoftext|>"),
            ("It's rare to find someone else into [Niche Hobby].",
                "Tell me about it! How did you discover it?<|endoftext|>"),
            ("What's your 'hot take' on [Shared Interest Topic]?",
                "Okay, controversially, I think [Hot Take Opinion]. What's yours?<|endoftext|>"),
            ("Since we both like [Place Type], what's your favorite one?",
                "Probably [Specific Place]. Love the atmosphere. Yours?<|endoftext|>"),
            ("Let's talk more about [Shared Interest]. What got you started?",
                "It was actually [Person/Event] that got me into it. How about you?<|endoftext|>"),

            // --- More suggestions ---
            ("We could hit up trivia night sometime, test our knowledge.",
                "I love trivia! Usually terrible at it, but it's fun. Where do you play?<|endoftext|>"),
            ("Maybe a wine tasting event?", "Ooh, classy! I'd be interested. Know of any coming up?<|endoftext|>"),
            ("How about volunteering together for a cause we both like?",
                "That's a really great idea. Which organization were you thinking?<|endoftext|>"),
            ("We could check out that retro arcade bar.", "Yes! Love those old games. When are you free?<|endoftext|>"),
            ("Want to go for a bike ride along the river trail?",
                "Sounds perfect on a nice day. What part of the trail?<|endoftext|>"),
            ("Maybe take a cooking class together?",
                "That could be hilarious or amazing. What kind of cuisine?<|endoftext|>"),
            ("How about visiting the botanical gardens?",
                "Sounds lovely and peaceful. I haven't been in ages.<|endoftext|>"),
            ("We could go check out an open mic night.",
                "Could be interesting! See some local talent. Know any good spots?<|endoftext|>"),
            ("Maybe browse that huge antique mall?",
                "I could get lost in there for hours! Sounds fun. Weekend maybe?<|endoftext|>"),
            ("Want to try kayaking/canoeing on the lake?",
                "Definitely! I haven't done that in a while. Do you have gear or need to rent?<|endoftext|>"),

            // --- Final batch to hit 400 ---
            ("You mentioned liking spicy food. Have you tried [Restaurant Name]?",
                "Not yet, but heard it's intense! Is it worth the hype?<|endoftext|>"),
            ("So, fellow night owl? What keeps you up?",
                "Usually reading or just getting lost online. You?<|endoftext|>"),
            ("We both like early mornings? What's your routine?",
                "Coffee, maybe a quick workout or walk. Peaceful time. Yours?<|endoftext|>"),
            ("You're also into minimalism?",
                "Trying to be! Decluttering feels good. What prompted your interest?<|endoftext|>"),
            ("What's your favorite thing about [Shared Season, e.g., Autumn]?",
                "The crisp air and the colors, for sure. You?<|endoftext|>"),
            ("Do you prefer fiction podcasts or non-fiction?",
                "Good mix, depends on the mood. Any non-fiction ones blow your mind recently?<|endoftext|>"),
            ("That photo with the cat is adorable. What's its name?",
                "That's Jasper! He's a character. Are you a cat person?<|endoftext|>"),
            ("Your bookshelf in the background looks impressive!",
                "Haha thanks! Trying to read them all. Spot any favorites?<|endoftext|>"),
            ("You said you like strategy games. Ever play chess?",
                "Yeah, I enjoy chess! Not great at it though. Do you play?<|endoftext|>"),
            ("Favorite type of workout? Strength, cardio, flexibility?",
                "Lean towards strength training, but know I need the others too! You?<|endoftext|>"),
            ("We seem to have a similar sense of humor based on your bio.",
                "Hope so! What part made you laugh?<|endoftext|>"),
            ("Both enjoy people-watching? Best spot in the city for it?",
                "Maybe that cafe corner on [Street Name]? Prime location. Your pick?<|endoftext|>"),
            ("You like stand-up comedy? Who are your favorite comedians?",
                "[Comedian 1] and [Comedian 2] always get me. Yours?<|endoftext|>"),
            ("Another person who enjoys rainy days!",
                "Yes! Perfect excuse to stay inside with a book. What do you like about them?<|endoftext|>"),
            ("You mentioned [Specific Dish]. Ever tried making it yourself?",
                "Attempted it once! Didn't go quite as planned. Have you?<|endoftext|>"),
            ("Cool that you're learning [Instrument]. How long have you been playing?",
                "About a year now, on and off. Still sound pretty rough! You play?<|endoftext|>"),
            ("Is [Shared TV Show] your favorite comfort watch too?",
                "Totally! Seen it probably 10 times. What's your go-to episode?<|endoftext|>"),
            ("What's the best travel advice you've received, fellow traveler?",
                "Pack light and always try the local food. Yours?<|endoftext|>"),
            ("Since we both like [Art Form], any exhibitions you're excited about?",
                "There's a [Artist/Style] one opening next month I want to see.<|endoftext|>"),
            ("Favorite thing to do on a lazy Sunday?",
                "Brunch, maybe a walk, then relaxing at home. Simple pleasures. You?<|endoftext|>"),
            ("You mentioned being into environmental causes. Any specific focus?",
                "Mainly reducing plastic waste and conservation. What about you?<|endoftext|>"),
            ("What's your go-to coffee order?", "Usually just a black Americano. Keep it simple. Yours?<|endoftext|>"),
            ("Do you prefer big music festivals or smaller intimate gigs?",
                "Smaller gigs, definitely. Better atmosphere. You?<|endoftext|>"),
            ("What's one book you think everyone should read?",
                "Tough one! Maybe 'Sapiens' by Harari. So insightful. Yours?<|endoftext|>"),
            ("If we went hiking, are you the fast-paced type or the stop-and-admire-the-view type?",
                "Definitely stop and admire! What's the rush? You?<|endoftext|>"),
            ("Favorite type of cuisine to cook at home?",
                "Italian is probably my go-to. Comfort food! What about you?<|endoftext|>"),
            ("What's the most interesting wildlife you've seen while outdoors?",
                "Saw a moose once! It was huge. Coolest thing you've spotted?<|endoftext|>"),
            ("Do you follow specific photographers or just enjoy the art form?",
                "Follow a few on Instagram, like [Photographer Name]. Any favorites?<|endoftext|>"),
            ("What board game absolutely destroys friendships?",
                "Monopoly, obviously! Or maybe Risk. Your vote?<|endoftext|>"),
            ("Let's settle this: best [Movie Franchise] film?",
                "Okay, controversial, but I'm going with [Film Title]. Thoughts?<|endoftext|>"),
            // --- Identifying Interests from Profile ---
            ("I saw you like hiking in your profile!", "Yeah, I love getting outdoors! Do you hike much?<|endoftext|>"),
            ("Your travel photos look amazing. Where's your favorite place you've been?",
                "Thanks! Probably Thailand. The food and beaches were incredible. Do you enjoy traveling?<|endoftext|>"),
            ("You mentioned you're a foodie. What's your favorite type of cuisine?",
                "Oh definitely! Hard to pick, but I love Italian and Vietnamese. How about you?<|endoftext|>"),
            ("Is that a guitar I see in your picture?", "Good eye! Yes, I play a bit. Are you musical?<|endoftext|>"),
            ("Your bio says you love dogs. Me too!",
                "Awesome! Dog people are the best people. Do you have one?<|endoftext|>"),
            ("Looks like you enjoy reading. Any good book recommendations?",
                "Always! Just finished 'Project Hail Mary'. Sci-fi fan? What genres do you like?<|endoftext|>"),
            ("You seem to be into photography based on your pics.",
                "I dabble! Mostly landscape stuff. Are you into photography too?<|endoftext|>"),
            ("Your taste in music seems cool from your anthem.",
                "Haha thanks! What kind of music do you listen to?<|endoftext|>"),
            ("Saw you like [Specific Movie/Show]. Big fan?",
                "Yes! Love that show/movie. Have you seen the latest season/sequel?<|endoftext|>"),
            ("You're into board games? Which ones?",
                "Yeah, love a good game night! Catan, Ticket to Ride, Wingspan. You?<|endoftext|>"),
            ("Your job in [Field] sounds interesting. Do you enjoy it?",
                "It has its moments! Keeps me busy. Does your work relate to any of your hobbies?<|endoftext|>"),
            ("Spotted the [Sports Team] gear. Are you a fan?",
                "Absolutely! Die-hard fan here. Do you follow them too?<|endoftext|>"),
            ("You like trying new restaurants too?",
                "Yes! Exploring the food scene is one of my favorite things. Any local gems you recommend?<|endoftext|>"),
            ("That concert photo looks fun! Who did you see?",
                "That was [Band Name]! They were amazing live. Do you go to many concerts?<|endoftext|>"),
            ("You mentioned volunteering. What kind of causes are you interested in?",
                "Mainly animal shelters and environmental stuff. What are you passionate about?<|endoftext|>"),

            // --- Expressing Shared Interest / Excitement ---
            ("No way, you like [Hobby] too?", "Yes! That's awesome. How did you get into it?<|endoftext|>"),
            ("Me too! I love [Activity].", "Cool! We should totally do that sometime.<|endoftext|>"),
            ("That's great, I'm also a big fan of [Genre/Artist/Author].",
                "Nice! Always good to meet someone with similar taste. Favorite song/book/movie?<|endoftext|>"),
            ("Wow, small world! I also enjoy [Specific Activity].",
                "Isn't it? What do you like most about it?<|endoftext|>"),
            ("It's cool that we both like [Thing].", "Totally! Makes conversation easier, right?<|endoftext|>"),
            ("Finally, someone else who appreciates [Niche Interest]!",
                "Haha, right? There aren't many of us! What got you interested?<|endoftext|>"),
            ("Oh awesome, another [Type of Interest] enthusiast!",
                "Yay! We should compare notes. What's your favorite aspect?<|endoftext|>"),
            ("Good taste! I love [Place/Food/Music] as well.",
                "Thanks! You too, clearly. What's your go-to [Related Item]?<|endoftext|>"),
            ("We seem to have that in common.", "Looks like it! What else are you into?<|endoftext|>"),
            ("It's nice to find someone who also enjoys [Activity].",
                "Definitely! Makes it easier to connect.<|endoftext|>"),
            ("You get it! [Thing] is the best.", "Totally agree! Why do you think it's so great?<|endoftext|>"),
            ("Solid choice. I'm also into [Thing].", "Nice! What draws you to it?<|endoftext|>"),
            ("Finding common ground already!", "Seems so! What other common ground might we find?<|endoftext|>"),
            ("You have great taste.", "Haha, thanks! Right back at you.<|endoftext|>"),
            ("Okay, this is promising. We both like [Thing].",
                "I was thinking the same thing! What's your favorite memory related to it?<|endoftext|>"),

            // --- Asking Follow-up Questions about Shared Interest ---
            ("So if we both like hiking, what's the best trail you've done?",
                "Ooh, tough one. Maybe [Trail Name] for the views. Yours?<|endoftext|>"),
            ("Since you also like cooking, what's your signature dish?",
                "I make a pretty mean lasagna! Do you have a specialty?<|endoftext|>"),
            ("What's your favorite [Author]'s book then?",
                "Probably [Book Title]. The way they write characters is amazing. Yours?<|endoftext|>"),
            ("How often do you get to go [Activity like Skiing/Surfing]?",
                "Not as often as I'd like! Maybe a few times a year. You?<|endoftext|>"),
            ("What other bands in that genre do you listen to?",
                "Lots! [Band 1], [Band 2], [Band 3]. Any favorites?<|endoftext|>"),
            ("If we both love travel, what's number one on your bucket list?",
                "Definitely seeing the Northern Lights. What about you?<|endoftext|>"),
            ("What kind of camera do you use for your photography?",
                "Just my phone mostly, but I have an old DSLR I break out sometimes. You?<|endoftext|>"),
            ("Favorite character in [Show/Movie Series]?",
                "Has to be [Character Name]. So well-written. Yours?<|endoftext|>"),
            ("What type of dog do you have / want?",
                "I have a rescue mutt, best dog ever! If you could get any breed, what would it be?<|endoftext|>"),
            ("What's the last concert you went to?",
                "Saw [Artist Name] last month. So good! Last one you saw?<|endoftext|>"),
            ("Do you prefer red or white wine?",
                "Usually red, but depends on the food! Do you have a preference?<|endoftext|>"),
            ("What's your favorite museum in the city?",
                "I really like the [Museum Name]. Have you been?<|endoftext|>"),
            ("How did you get started with [Hobby]?",
                "A friend introduced me years ago and I got hooked. What about you?<|endoftext|>"),
            ("What do you enjoy most about [Activity]?",
                "The peacefulness and the challenge. What draws you to it?<|endoftext|>"),
            ("Any particular coffee shops you recommend since we both like coffee?",
                "Oh yeah, [Cafe Name] makes an amazing latte. Know any hidden gems?<|endoftext|>"),

            // --- Suggesting Activities Based on Shared Interest ---
            ("Since we both love hiking, maybe we could hit a trail together sometime?",
                "I'd be down for that! Any particular trail in mind?<|endoftext|>"),
            ("We should grab coffee and talk books sometime.",
                "That sounds lovely! Are you free next week?<|endoftext|>"),
            ("How about we check out that new [Cuisine Type] restaurant?",
                "Yes! I've been wanting to try that place. When works for you?<|endoftext|>"),
            ("Maybe we could catch some live music together?",
                "Sounds like a great idea! Know any good shows coming up?<|endoftext|>"),
            ("We could have a board game night if you're up for it.",
                "Totally up for it! Do you have a favorite game place or play at home?<|endoftext|>"),
            ("Want to meet up at the dog park sometime?",
                "My dog would love that! Which park do you usually go to?<|endoftext|>"),
            ("We should go see a movie, since we have similar taste.",
                "Definitely! Anything good playing now you want to see?<|endoftext|>"),
            ("How about trying that brewery we both mentioned liking?",
                "Sounds like a plan! Are you free this weekend?<|endoftext|>"),
            ("Maybe we could cook together sometime?",
                "That could be fun! Risky, but fun. What should we make?<|endoftext|>"),
            ("We should visit that [Museum/Gallery] exhibit everyone's talking about.",
                "Oh, I wanted to see that! Let's do it. What day is good?<|endoftext|>"),
            ("Since we both like [Sport], maybe watch a game sometime?",
                "Yeah, that'd be cool! At a bar or grab tickets?<|endoftext|>"),
            ("Let's explore that neighborhood known for its street art.",
                "Great idea! I love street art. When are you thinking?<|endoftext|>"),
            ("We could check out that bookstore cafe.",
                "Perfect combo! I'm in. How about Saturday afternoon?<|endoftext|>"),
            ("Maybe a picnic in the park if the weather's nice?",
                "That sounds lovely and relaxed. Which park?<|endoftext|>"),
            ("Want to hit up the farmer's market this weekend?",
                "Yes! Love the farmer's market. Saturday or Sunday morning?<|endoftext|>"),

            // --- Comparing Experiences / Deeper Discussion ---
            ("What's the craziest thing that happened on one of your trips?",
                "Oh boy. Probably getting lost in Tokyo subway system! You?<|endoftext|>"),
            ("What's the most challenging hike you've ever done?",
                "[Trail Name] was brutal but rewarding. What about you?<|endoftext|>"),
            ("Do you prefer fiction or non-fiction books?", "Mostly fiction, need that escapism! You?<|endoftext|>"),
            ("Cats or dogs? Or both?",
                "Love both, but probably lean slightly more towards dogs. Your preference?<|endoftext|>"),
            ("What instrument do you wish you could play?",
                "Piano, definitely. Seems so expressive. You?<|endoftext|>"),
            ("Is there a particular artist whose work really speaks to you?",
                "[Artist Name]'s stuff is incredible. The colors! Anyone for you?<|endoftext|>"),
            ("Favorite thing to photograph?",
                "People, candids especially. Capturing moments. What do you like shooting?<|endoftext|>"),
            ("Best concert memory?", "Seeing [Band Name] front row. Unforgettable energy. Yours?<|endoftext|>"),
            ("Spicy food: yes or no?", "Absolutely yes! The spicier the better. How about you?<|endoftext|>"),
            ("What's one dish you've always wanted to learn how to cook perfectly?",
                "Authentic Pad Thai. It's harder than it looks! You?<|endoftext|>"),
            ("Do you rewatch movies/shows or always look for something new?",
                "I'm a rewatcher! Comfort viewing. You?<|endoftext|>"),
            ("What makes a board game fun for you? Strategy or luck?",
                "Good mix of both, but lean towards strategy. Your preference?<|endoftext|>"),
            ("What's the funniest thing your pet has ever done?",
                "My cat once fell asleep face-first in his food bowl. What about yours?<|endoftext|>"),
            ("Do you prefer playing sports or watching them?", "Playing, definitely. More engaging. You?<|endoftext|>"),
            ("Beach vacation or mountain retreat?",
                "Mountains for me. Love the air and the views. Your ideal getaway?<|endoftext|>"),

            // --- General Conversation about Having Things in Common ---
            ("It's cool finding someone with similar interests.",
                "Yeah, it definitely makes starting a conversation easier!<|endoftext|>"),
            ("Seems like we might get along based on our hobbies.",
                "I was thinking the same! What other hobbies do you have?<|endoftext|>"),
            ("Do you find you connect better with people who share your interests?",
                "Usually, yeah. It provides an instant shared language.<|endoftext|>"),
            ("What's one interest you wish more people shared with you?",
                "Maybe my love for obscure 80s synth-pop? Haha. You?<|endoftext|>"),
            ("Is having common interests important to you in a connection?",
                "It helps, but different interests can be cool too. What do you think?<|endoftext|>"),
            ("So, besides [Shared Interest 1] and [Shared Interest 2], what else are you passionate about?",
                "I'm also really into sustainable living and gardening. How about you?<|endoftext|>"),
            ("It's refreshing to chat with someone who gets my reference about [Niche Topic].",
                "Haha, glad I could! Not many people catch those.<|endoftext|>"),
            ("Our potential date ideas list is already growing!",
                "Right? Hiking, coffee, checking out that band... choices!<|endoftext|>"),
            ("What's an interest you have that might surprise people?",
                "I'm secretly really into competitive bird watching. It's intense! You?<|endoftext|>"),
            ("Do you prefer exploring shared interests or learning about new ones from someone?",
                "A bit of both is ideal, I think. Keeps things interesting.<|endoftext|>"),

            // --- More Variations on Identifying/Reacting ---
            ("I noticed you're into [Specific Activity] from your photos.",
                "Yep, love doing that! Have you tried it?<|endoftext|>"),
            ("Your bio mentions a love for coffee. Fellow addict here!",
                "Haha, definitely addicted! What's your usual order?<|endoftext|>"),
            ("Seems like we both enjoy being outdoors.",
                "That's great! What's your favorite outdoor activity?<|endoftext|>"),
            ("Are you also a fan of cheesy sci-fi movies?",
                "Guilty pleasure! Some are just too good/bad. Any favorites?<|endoftext|>"),
            ("So you like spicy food too? Finally, someone who understands.",
                "Right? Life's too short for bland food! How spicy can you handle?<|endoftext|>"),
            ("I'm also learning [Language/Skill]. How's it going for you?",
                "Slowly but surely! It's challenging. What resources are you using?<|endoftext|>"),
            ("You mentioned you like to cook. Sweet or savory?",
                "Definitely lean more savory, but I make a mean chocolate cake. You?<|endoftext|>"),
            ("Big [Genre] music fan here too.", "Awesome! Who are your top artists in that genre?<|endoftext|>"),
            ("Looks like we frequent the same [Type of Place, e.g., park, cafe].",
                "Maybe we've seen each other around! What do you like about it?<|endoftext|>"),
            ("Another [City/State] sports fan! Which team?",
                "Gotta support [Team Name]! Through thick and thin. You?<|endoftext|>"),
            ("You're into vintage shopping? Me too!", "Oh cool! Found any amazing treasures lately?<|endoftext|>"),
            ("Camping - love it or hate it?",
                "Love it! Getting away from everything is great. Your take?<|endoftext|>"),
            ("Your interest in [Historical Period/Topic] is cool.",
                "Thanks! I find it fascinating. What periods interest you?<|endoftext|>"),
            ("Saw you're into yoga/meditation.", "Yeah, helps me stay centered. Do you practice?<|endoftext|>"),
            ("We share an appreciation for good whiskey/wine/beer.",
                "Excellent! What's your go-to bottle or brewery?<|endoftext|>"),

            // --- Fillers and Continuations Focused on Interests ---
            ("Tell me more about your interest in [Hobby].",
                "Well, I started about [Timeframe] ago because... [brief story].<|endoftext|>"),
            ("That's interesting. What else do you like about [Activity]?",
                "I also like the community around it. Met some cool people.<|endoftext|>"),
            ("So, regarding [Shared Interest], have you ever [Specific Experience]?",
                "Oh yeah, I did that last year! It was [adjective]. Have you?<|endoftext|>"),
            ("What other similar [Books/Movies/Bands] would you recommend?",
                "If you like that, you should definitely check out [Recommendation].<|endoftext|>"),
            ("How does [Hobby] fit into your typical week?",
                "Try to make time for it a couple evenings or on the weekend.<|endoftext|>"),
            ("Any funny stories related to your love for [Interest]?",
                "One time, when I was [Doing Activity], this hilarious thing happened...<|endoftext|>"),
            ("What's the best part about being a fan of [Team/Artist]?",
                "The community and the shared excitement, for sure.<|endoftext|>"),
            ("What's next on your [Travel/Reading/Hiking] list?",
                "Hoping to tackle [Specific Goal] soon! What about you?<|endoftext|>"),
            ("Is [Interest] something you do alone or with friends?",
                "Bit of both, depends on the mood and activity.<|endoftext|>"),
            ("What's the most rewarding part of [Hobby] for you?",
                "Just the feeling of accomplishment when you finish something.<|endoftext|>"),
            ("If you could only do one [Activity Type] for the rest of your life, what?",
                "Oof, tough call. Probably [Activity]. It covers a lot.<|endoftext|>"),
            ("What got you hooked on [Genre/Franchise]?",
                "The world-building is just incredible. Sucked me right in.<|endoftext|>"),
            ("Do you prefer [Option A] or [Option B] within that interest?",
                "Definitely [Option A]. It just resonates more. You?<|endoftext|>"),
            ("What resources did you use to learn [Skill]?",
                "Mostly online tutorials and just lots of practice! You?<|endoftext|>"),
            ("Let's circle back to [Shared Interest]. You mentioned...",
                "Right! So about that, I think... [continues thought].<|endoftext|>"),

            // --- Generating more pairs to reach 400, varying phrasing ---
            ("You like craft beer? Any local breweries you love?",
                "Definitely! [Brewery Name] is my favorite right now. Have you been?<|endoftext|>"),
            ("Saw you're into fitness. What's your preferred workout?",
                "Mix it up, but I enjoy weightlifting and running. You?<|endoftext|>"),
            ("Gardening, huh? What do you grow?",
                "Mostly herbs and vegetables. Trying tomatoes this year! Do you have a garden?<|endoftext|>"),
            ("Another history buff! Favorite era?", "Love ancient Rome and Egypt. So much drama! Yours?<|endoftext|>"),
            ("You paint/draw? What style?",
                "Mostly abstract acrylics. Still learning! Do you create art?<|endoftext|>"),
            ("You mentioned podcasts. Any recommendations?",
                "Currently hooked on [Podcast Name]. What are you listening to?<|endoftext|>"),
            ("DIY projects? What have you made?",
                "Built my own bookshelf recently! Pretty proud. Are you handy?<|endoftext|>"),
            ("So you're a fellow theatre geek?",
                "Totally! Love a good musical or play. Seen anything great lately?<|endoftext|>"),
            ("You like stargazing too?", "Yes! It's so peaceful. Do you have a telescope?<|endoftext|>"),
            ("Anime fan? What are your top series?",
                "Big time! Death Note, Attack on Titan, Fullmetal Alchemist. Yours?<|endoftext|>"),
            ("Also into documentaries? Any standouts?",
                "'My Octopus Teacher' was amazing. Seen any powerful ones recently?<|endoftext|>"),
            ("You enjoy volunteering. That's admirable.",
                "Thanks! It feels good to give back. What causes do you care about?<|endoftext|>"),
            ("Seems we both appreciate a good cup of tea.", "Absolutely! What's your favorite blend?<|endoftext|>"),
            ("You're into motorcycles? What do you ride?",
                "Got a [Bike Type/Brand]. Nothing beats hitting the open road. Do you ride?<|endoftext|>"),
            ("Fellow car enthusiast? What's your dream car?",
                "Hard question! Maybe a classic Porsche 911. Yours?<|endoftext|>"),
            ("You like puzzles? Jigsaws or crosswords?",
                "Love both! Jigsaws for relaxing, crosswords for thinking. You?<|endoftext|>"),
            ("It's cool you're learning sign language.",
                "Thanks! It's challenging but rewarding. Know any signs?<|endoftext|>"),
            ("You enjoy birdwatching too?",
                "Yes! It's surprisingly engaging. Spotted anything interesting lately?<|endoftext|>"),
            ("Also a fan of architecture?",
                "Definitely. Love exploring different building styles. Favorite style?<|endoftext|>"),
            ("You seem to like spending time by the water.",
                "Yeah, find it very calming. Beach or lake person?<|endoftext|>"),

            ("So, same taste in music. What else might we agree on?",
                "Good question! How do you feel about pineapple on pizza?<|endoftext|>"),
            ("Given our shared love for [Activity], I bet we'd get along.",
                "Seems likely! What's your favorite part about [Activity]?<|endoftext|>"),
            ("Finding common ground is making this easy!",
                "Totally agree! What's an interest of yours I might not guess?<|endoftext|>"),
            ("We should definitely compare notes on [Hobby].",
                "For sure. What's the latest project/book/game you're working on/reading/playing?<|endoftext|>"),
            ("Okay, we need to discuss our mutual love for [Food Item].",
                "Yes! Where's the best place to get it around here, in your opinion?<|endoftext|>"),
            ("This shared interest in [Topic] is pretty cool.",
                "Right? What specifically about it fascinates you?<|endoftext|>"),
            ("It's rare to find someone else into [Niche Hobby].",
                "Tell me about it! How did you discover it?<|endoftext|>"),
            ("What's your 'hot take' on [Shared Interest Topic]?",
                "Okay, controversially, I think [Hot Take Opinion]. What's yours?<|endoftext|>"),
            ("Since we both like [Place Type], what's your favorite one?",
                "Probably [Specific Place]. Love the atmosphere. Yours?<|endoftext|>"),
            ("Let's talk more about [Shared Interest]. What got you started?",
                "It was actually [Person/Event] that got me into it. How about you?<|endoftext|>"),

            // --- More suggestions ---
            ("We could hit up trivia night sometime, test our knowledge.",
                "I love trivia! Usually terrible at it, but it's fun. Where do you play?<|endoftext|>"),
            ("Maybe a wine tasting event?", "Ooh, classy! I'd be interested. Know of any coming up?<|endoftext|>"),
            ("How about volunteering together for a cause we both like?",
                "That's a really great idea. Which organization were you thinking?<|endoftext|>"),
            ("We could check out that retro arcade bar.", "Yes! Love those old games. When are you free?<|endoftext|>"),
            ("Want to go for a bike ride along the river trail?",
                "Sounds perfect on a nice day. What part of the trail?<|endoftext|>"),
            ("Maybe take a cooking class together?",
                "That could be hilarious or amazing. What kind of cuisine?<|endoftext|>"),
            ("How about visiting the botanical gardens?",
                "Sounds lovely and peaceful. I haven't been in ages.<|endoftext|>"),
            ("We could go check out an open mic night.",
                "Could be interesting! See some local talent. Know any good spots?<|endoftext|>"),
            ("Maybe browse that huge antique mall?",
                "I could get lost in there for hours! Sounds fun. Weekend maybe?<|endoftext|>"),
            ("Want to try kayaking/canoeing on the lake?",
                "Definitely! I haven't done that in a while. Do you have gear or need to rent?<|endoftext|>"),

            // --- Final batch to hit 400 ---
            ("You mentioned liking spicy food. Have you tried [Restaurant Name]?",
                "Not yet, but heard it's intense! Is it worth the hype?<|endoftext|>"),
            ("So, fellow night owl? What keeps you up?",
                "Usually reading or just getting lost online. You?<|endoftext|>"),
            ("We both like early mornings? What's your routine?",
                "Coffee, maybe a quick workout or walk. Peaceful time. Yours?<|endoftext|>"),
            ("You're also into minimalism?",
                "Trying to be! Decluttering feels good. What prompted your interest?<|endoftext|>"),
            ("What's your favorite thing about [Shared Season, e.g., Autumn]?",
                "The crisp air and the colors, for sure. You?<|endoftext|>"),
            ("Do you prefer fiction podcasts or non-fiction?",
                "Good mix, depends on the mood. Any non-fiction ones blow your mind recently?<|endoftext|>"),
            ("That photo with the cat is adorable. What's its name?",
                "That's Jasper! He's a character. Are you a cat person?<|endoftext|>"),
            ("Your bookshelf in the background looks impressive!",
                "Haha thanks! Trying to read them all. Spot any favorites?<|endoftext|>"),
            ("You said you like strategy games. Ever play chess?",
                "Yeah, I enjoy chess! Not great at it though. Do you play?<|endoftext|>"),
            ("Favorite type of workout? Strength, cardio, flexibility?",
                "Lean towards strength training, but know I need the others too! You?<|endoftext|>"),
            ("We seem to have a similar sense of humor based on your bio.",
                "Hope so! What part made you laugh?<|endoftext|>"),
            ("Both enjoy people-watching? Best spot in the city for it?",
                "Maybe that cafe corner on [Street Name]? Prime location. Your pick?<|endoftext|>"),
            ("You like stand-up comedy? Who are your favorite comedians?",
                "[Comedian 1] and [Comedian 2] always get me. Yours?<|endoftext|>"),
            ("Another person who enjoys rainy days!",
                "Yes! Perfect excuse to stay inside with a book. What do you like about them?<|endoftext|>"),
            ("You mentioned [Specific Dish]. Ever tried making it yourself?",
                "Attempted it once! Didn't go quite as planned. Have you?<|endoftext|>"),
            ("Cool that you're learning [Instrument]. How long have you been playing?",
                "About a year now, on and off. Still sound pretty rough! You play?<|endoftext|>"),
            ("Is [Shared TV Show] your favorite comfort watch too?",
                "Totally! Seen it probably 10 times. What's your go-to episode?<|endoftext|>"),
            ("What's the best travel advice you've received, fellow traveler?",
                "Pack light and always try the local food. Yours?<|endoftext|>"),
            ("Since we both like [Art Form], any exhibitions you're excited about?",
                "There's a [Artist/Style] one opening next month I want to see.<|endoftext|>"),
            ("Favorite thing to do on a lazy Sunday?",
                "Brunch, maybe a walk, then relaxing at home. Simple pleasures. You?<|endoftext|>"),
            ("You mentioned being into environmental causes. Any specific focus?",
                "Mainly reducing plastic waste and conservation. What about you?<|endoftext|>"),
            ("What's your go-to coffee order?", "Usually just a black Americano. Keep it simple. Yours?<|endoftext|>"),
            ("Do you prefer big music festivals or smaller intimate gigs?",
                "Smaller gigs, definitely. Better atmosphere. You?<|endoftext|>"),
            ("What's one book you think everyone should read?",
                "Tough one! Maybe 'Sapiens' by Harari. So insightful. Yours?<|endoftext|>"),
            ("If we went hiking, are you the fast-paced type or the stop-and-admire-the-view type?",
                "Definitely stop and admire! What's the rush? You?<|endoftext|>"),
            ("Favorite type of cuisine to cook at home?",
                "Italian is probably my go-to. Comfort food! What about you?<|endoftext|>"),
            ("What's the most interesting wildlife you've seen while outdoors?",
                "Saw a moose once! It was huge. Coolest thing you've spotted?<|endoftext|>"),
            ("Do you follow specific photographers or just enjoy the art form?",
                "Follow a few on Instagram, like [Photographer Name]. Any favorites?<|endoftext|>"),
            ("What board game absolutely destroys friendships?",
                "Monopoly, obviously! Or maybe Risk. Your vote?<|endoftext|>"),
            ("Let's settle this: best [Movie Franchise] film?",
                "Okay, controversial, but I'm going with [Film Title]. Thoughts?<|endoftext|>"),
        };
    }
}